services:
  server:
    image: 'nikolaik/python-nodejs:python3.8-nodejs18-slim'
    command: bash start.sh
    working_dir: /app
    environment:
      WEB_RTC_SERVER_PORT: 10011
      WEB_RTC_SERVER_IP: 0.0.0.0
      WEB_RTC_SERVER_ANNOUNCED_IP: 127.0.0.1
    ports:
      - '3000:3000'
      - '10011:10011'
    volumes:
      - './:/app'
